### ISSUE TITLE
Using »Storage: Drop« event filter is triggered even though entry creation is unsuccessful

### ISSUE THREAD

**Issue by animaux** [hananils/storage#63]
@nilshoerrmann @michael-e (This is possibly a problem with my templates, still I’m thankful for any hints)

I am using storage for a cart. In the order process I have a final order page where customer enter their data. Attached to the page is the `Storage: Drop` event including the hidden input `<input type="hidden" name="storage-action[drop][tuete]" value="1"/>`.

I expect the event filter only to be triggered when entry creation is successful e. g. all required fields are filled in. But apparently the filter is triggered even when there’s an error, which leaves the customer with an empty shopping cart and no form, thinking he actually placed the order but not receiving any confirmation mails or else.

Am I doing something basic wrong?

**Comment by michael-e** [comment]
In simple words: You are doing it wrong. :-)

You should **either** use the provided event filter (which hooks into the `EventFinalSaveFilter` delegate, so it will only be triggered if the event is successful) **or** you may send `['storage-action']['drop']` (either by `GET` or `POST`) inorder to drop the storage. The latter method is just an additional way to drop things, but it is not needed for most workflows.

**Comment by animaux** [comment]
> In simple words: You are doing it wrong. :-)

I was very much hoping so :)

But using the event filter only, without the hidden input, didn’t drop the storage. Will try again …

**Comment by michael-e** [comment]
Yep, please try again. As far as I have seen (in the code, reverse engineering…), it should drop the storage.

**Comment by animaux** [comment]
@michael-e Forgive my utter stupidity, but do you mean using the `Storage: Drop` event filter WITHOUT the mentioned hidden input field should do the trick? After trying again it doesn’t :(

**Comment by animaux** [comment]
Doesn’t drop without the hidden field :(

**Comment by michael-e** [comment]
Oh, I was wrong. I am sorry.

**Comment by animaux** [comment]
Ehm, ok, but how?

**Comment by michael-e** [comment]
This is the way it works:

```php
if(in_array('storage-drop', $context['event']->eParamFILTERS)){

    $drop_request = $_REQUEST['storage-action']['drop'];

    if(is_array($drop_request)) {
        $s = new Storage();
        $s->drop($drop_request);
    }
}
```

Which means: If the event filter is triggered **and** `$_REQUEST['storage-action']['drop']` is an array (!), then the storage will be dropped.

**Comment by michael-e** [comment]
But still this means that it should only happen when the `EventFinalSaveFilter` delegate is triggered, i.e. when the (save?) event was successful.

**Comment by animaux** [comment]
Does »Save« apply to newly created entries too? (forgive my lack of insight into the inner workings of symphony delegates)

**Comment by michael-e** [comment]
Yep. There are basically three delegates resposible for filters:

1. EventPreSaveFilter (triggered before saving is attempted—so this is used by security filters, for example)
2. EventPostSaveFilter (triggered after saving, "passive" filter)
3. EventFinalSaveFilter (triggered even afterwards, "passive" filter)

These filters do the same for new and existing entries.

**Comment by animaux** [comment]
Thanks for explaining, I begin to get a picture. So the drop happening anyway is a bug in `storage` then?

**Comment by michael-e** [comment]
Good question. :-) Give me a some minutes.

**Comment by animaux** [comment]
Sure! :shower:

**Comment by michael-e** [comment]
Hmmm, I don't get it. If I look at the `__doit` function (in `/symphony/lib/toolkit/events/class.event.section.php`), I see the following:

```php
// Validate the data. `$entry->checkPostData` loops over all fields calling
// checkPostFieldData function. If the return of the function is `__ENTRY_FIELD_ERROR__`
// then abort the event, adding the error messages to the `$result`.
if(__ENTRY_FIELD_ERROR__ == $entry->checkPostData($fields, $errors, ($entry->get('id') ? true : false))) {
	$result = self::appendErrors($result, $fields, $errors, $post_values);
	return false;
}

// If the data is good, process the data, almost ready to save it to the
// Database. If processing fails, abort the event and display the errors
else if(__ENTRY_OK__ != $entry->setDataFromPost($fields, $errors, false, ($entry->get('id') ? true : false))) {
	$result = self::appendErrors($result, $fields, $errors, $post_values);
	return false;
}

// Data is checked, data has been processed, by trying to save the
// Entry caused an error to occur, so abort and return.
else if($entry->commit() === false) {
	$result->setAttribute('result', 'error');
	$result->appendChild(new XMLElement('message', __('Unknown errors where encountered when saving.')));

	if(isset($post_values) && is_object($post_values)) {
		$result->appendChild($post_values);
	}

	return false;
}

// Entry was created, add the good news to the return `$result`
else {
	$result->setAttributeArray(array(
		'result' => 'success',
		'type' => (isset($entry_id) ? 'edited' : 'created'),
		'id' => $entry->get('id')
	));
	$result->appendChild(new XMLElement('message',
		(isset($entry_id)
			? __('Entry edited successfully.')
			: __('Entry created successfully.'))
	));
}

// PASSIVE FILTERS ONLY AT THIS STAGE. ENTRY HAS ALREADY BEEN CREATED.
if(in_array('send-email', $this->eParamFILTERS) && !in_array('expect-multiple', $this->eParamFILTERS)) {
	$result = $this->processSendMailFilter($result, $_POST['send-email'], $fields, $section, $entry);
}

$result = $this->processPostSaveFilters($result, $fields, $entry);
$result = $this->processFinalSaveFilters($result, $fields, $entry);
```

This means that if field validation fails, or the entry can not committed for unknown reasons, the function will return `false`, and the post/final save filters won't be triggered.

So I will take a look at the storage extension now, again. It's been a while since I implemented it…

**Comment by animaux** [comment]
Tausend Dank!

**Comment by michael-e** [comment]
Which (storage) events and/or filters do you have attached to your page?

**Comment by michael-e** [comment]
I think it works like this:

If you attach the storage event to a page and send `$_REQUEST['storage-action']['drop']`, the storage will be dropped, no matter which other events or filters are attached.

If you attach a different event (saving data, for example) which has the `Storage: Drop` filter, and you use a hidden field in your form like `<input type="hidden" name="storage-action[drop][cart]" value="1">`, then the stroage will be dropped **only if the event is successful**. 

So in my implementation I have two different pages:

1. `Cart` (`Storage: Action` event attached)
2. `Order` (`Order: New` event attached, with the above hidden field sent by the form)

**Comment by animaux** [comment]
`Storage Action` is attached to the page, as well as `Bestellung abschicken` which itself includes

+ Can of Spam
+ Send Email Template: Bestellbestätigung
+ Send Email Template: Bestellung eingegangen
+ Storage Drop
+ Filter XSS …

**Comment by animaux** [comment]
I’m feeling a d’oh-moment coming along. Hang in a second.

**Comment by michael-e** [comment]
To be precise, I have three pages:

1. `Stuff`—well, it could be "store" as well (`Storage: Action` event attached); you can browse items and add it to storage here
2. `Cart` (`Storage: Action` event attached); here you can see the storage and update item counts or drop everything (using a URL with a query string)
3. `Order` (`Order: New` event attached, with the above hidden field sent by the form); this is the final page which includes the "order now" button

**Comment by animaux** [comment]
Ok, same here mostly. So you have the `Storage: Drop` filter attached to the `Order: New`event (plus hidden field)?

**Comment by animaux** [comment]
(on Page No. 3.)

**Comment by michael-e** [comment]
Yep, exactly.

**Comment by animaux** [comment]
Me too … with the result mentioned above :(

**Comment by michael-e** [comment]
Are you really sure that this is your only event? So you do not have `Storage: Action` attached to this page?

**Comment by animaux** [comment]
I did have `Storage: Action` … ürghs … rechecking.

**Comment by animaux** [comment]
IT WORKS!

**Comment by animaux** [comment]
Thanks so much for your patience. Sorry if I missed this point earlier in our dialogue …

**Comment by animaux** [comment]
I thought the `Storage: Action` event was neccessary to make the drop possible.

**Comment by animaux** [comment]
Hah, a great way to end the day :) thanks again, and good night. And sorry for being so dim today …

**Comment by michael-e** [comment]
Ah, the filter has been added as an option, later. And we didn't want to change the way things work in the main event.

I am glad that I could help in the end.

**Comment by animaux** [comment]
You sure did :)
